#!/bin/bash




# -------- DEFINITIONS --------

#exit on error
set -e

#current executable directory
CXD=$(dirname $(readlink -f $0))
pCXD=$(dirname $CXD)

#paths
OUT=$pCXD/out
TMP=$OUT/tmp

#config library
CONFIG_CLONE_URL='https://github.com/iasebsil83/Config'
CONFIG_VERSION='python'






# -------- PREPARE ENVIRONMENT --------

#clean
$CXD/clean

#remove previous generations
rm --recursive --force $OUT/src
if [[ ! -d $TMP ]]; then mkdir --parents $TMP; fi

#get config library
if [[ ! -f $TMP/config.py ]]; then
	cd $TMP
	git clone --branch $CONFIG_VERSION $CONFIG_CLONE_URL --quiet config
	mv config/lib/config.py .
	rm --recursive --force config
fi






# -------- EXECUTION --------

#syscalls and its inv
$CXD/genSyscalls x86_64
